In [12]:
import numpy as np
from numpy import pi
import numpy
import scipy
import qiskit
from scipy.stats import unitary_group
from qiskit import transpile
import scipy.linalg as sl
import numpy.linalg as nl
from scipy.linalg import cossin
from qiskit.quantum_info import Operator, Statevector
from qiskit import QuantumCircuit
from qiskit.circuit.library import UGate,UCPauliRotGate
from qiskit import QuantumCircuit, transpile
from qiskit.quantum_info import Operator
import sys
sys.path.append('./src')
##
import utils_synth
import oracle_synth
import lcu
import lchs
import _quick_test
import importlib
importlib.reload(lcu)
importlib.reload(lchs)
importlib.reload(utils_synth)
importlib.reload(oracle_synth)
importlib.reload(_quick_test)
##
from utils_synth import *
from oracle_synth import *
from lchs import *
from src.lcu import *
from _quick_test import *

rng = numpy.random.default_rng(4290962056973923694427)
np.set_printoptions(precision=8, suppress=True)

XX = numpy.kron(X(), X())
YY = numpy.kron(Y(), Y())
ZZ = numpy.kron(Z(), Z())

In [16]:
def XXYYZZ_mat(c0,c1,c2):
    return scipy.linalg.expm(1j*(c0*XX+c1*YY+c2*ZZ))

def XXYYZZ_circ(c0,c1,c2):
    prod = np.kron(I(), RZ(-pi/2))
    prod = CNOTINV() @ prod
    prod = np.kron(RZ(pi/2 - 2*c2), RY(2*c0 - pi/2)) @ prod
    prod = CNOT() @ prod
    prod = np.kron(I(), RY(pi/2 - 2*c1)) @ prod
    prod = CNOTINV() @ prod
    prod = np.kron(RZ(pi/2), I()) @ prod
    return prod*numpy.exp(1j*pi/4)

c0,c1,c2 = rng.uniform(-pi,pi,3)
ans = XXYYZZ_mat(c0,c1,c2)
circ_op = XXYYZZ_circ(c0,c1,c2)
numpy.linalg.norm(ans - circ_op)

4.058511531260178e-16

In [18]:
RZ(-pi/2) @ np.array([[1,2],[3,4]])

array([[0.70710678+0.70710678j, 1.41421356+1.41421356j],
       [2.12132034-2.12132034j, 2.82842712-2.82842712j]])

In [24]:
np.array([[1,2],[3,4]]) @ RZ(pi/2)

array([[0.70710678-0.70710678j, 1.41421356+1.41421356j],
       [2.12132034-2.12132034j, 2.82842712+2.82842712j]])

In [25]:
RZ(pi/2)

array([[0.70710678-0.70710678j, 0.        +0.j        ],
       [0.        +0.j        , 0.70710678+0.70710678j]])

In [27]:
rz11 = numpy.sqrt(1/2)+1j*numpy.sqrt(2)
rz00 = numpy.sqrt(2)-1j*numpy.sqrt(2)
rz11,rz00

((0.7071067811865476+1.4142135623730951j),
 (1.4142135623730951-1.4142135623730951j))

In [28]:
circ = QuantumCircuit(2)
circ.global_phase

0.0