In [43]:
import numpy as np
from numpy import pi
import numpy
import scipy
import qiskit
from scipy.stats import unitary_group
from qiskit import transpile
import scipy.linalg as sl
import numpy.linalg as nl
from scipy.linalg import cossin
from qiskit.quantum_info import Operator, Statevector
from qiskit import QuantumCircuit
from qiskit.circuit.library import UGate,UCPauliRotGate
from qiskit import QuantumCircuit, transpile
from qiskit.quantum_info import Operator
import sys
sys.path.append('./src')
##
import utils_synth
import oracle_synth
import lcu
import lchs
import _quick_test
import importlib
importlib.reload(lcu)
importlib.reload(lchs)
importlib.reload(utils_synth)
importlib.reload(oracle_synth)
importlib.reload(_quick_test)
##
from utils_synth import *
from oracle_synth import *
from lchs import *
from src.lcu import *
from _quick_test import *

rng = numpy.random.default_rng(4290962056973923694427)
np.set_printoptions(precision=8, suppress=True)

XX = numpy.kron(X(), X())
YY = numpy.kron(Y(), Y())
ZZ = numpy.kron(Z(), Z())

In [53]:
lam = 0.5
gamma = 0.1
n = 2
time_tau = 1
ham = hams_fullmat(gamma, lam, n)

scipy_sol = scipy.linalg.expm(-1j * time_tau * ham)
my_sol_circ = expmiht_approx(n, time_tau, gamma, lam, order=2, verbose=1)
my_sol = Operator(my_sol_circ).data

error = np.linalg.norm( scipy_sol - Operator(my_sol).data )
error

  Ham. Sim. Error Upper Bound= 0.0001666666666666667


0.14124482249637726

In [54]:
my_sol

array([[ 0.99500417+0.j        ,  0.04786269-0.08761207j,
         0.        +0.j        ,  0.        +0.j        ],
       [-0.04786269-0.08761207j,  0.99500417-0.j        ,
         0.        +0.j        ,  0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
         0.99500417+0.j        ,  0.04786269-0.08761207j],
       [ 0.        +0.j        ,  0.        +0.j        ,
        -0.04786269-0.08761207j,  0.99500417-0.j        ]])

In [55]:
scipy_sol

array([[ 0.99500833-0.j        ,  0.04778294-0.08746609j,
        -0.00269476-0.00419685j, -0.000166  +0.00001177j],
       [-0.04778294-0.08746609j,  0.99002082+0.j        ,
         0.04770316-0.08732005j, -0.00269476-0.00419685j],
       [-0.00269476+0.00419685j, -0.04770316-0.08732005j,
         0.99002082+0.j        ,  0.04778294-0.08746609j],
       [ 0.000166  +0.00001177j, -0.00269476+0.00419685j,
        -0.04778294-0.08746609j,  0.99500833+0.j        ]])

In [31]:

def tensor_power(mat:numpy.ndarray, power:int):
    if power == 0:
        return numpy.eye(mat.shape[0])
    if power == 1:
        return mat
    return numpy.kron(mat, tensor_power(mat, power-1))

tensor_power(np.identity(2), 3)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
P(-lam) @ H() @ Z() @ H() @ P(lam)

array([[-0.        +0.j        ,  0.87758256+0.47942554j],
       [ 0.87758256-0.47942554j,  0.        -0.j        ]])